# Generated by Django 3.2.10 on 2022-08-08 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=12, unique=True)),
                ('StudentCode', models.CharField(default='', max_length=12, unique=True)),
                ('Email', models.CharField(max_length=256, unique=True)),
                ('IdType', models.CharField(default='C.C', max_length=8)),
                ('FullName', models.CharField(max_length=512)),
                ('Password', models.CharField(max_length=256)),
                ('Auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
